name: vue-renueva
recipe: lamp
config:
  type: php:8.1
  webroot: ./dist
services:
  appserver:
    type: php:8.1
    ssl: true
  node:
    type: node:19
tooling:
  node:
    service: node
  npm:
    service: node